[package]
name = "gridish"
version = "0.1.0"
edition = "2024"

[features]
tetrads = []

[dependencies]
geo-types = "0.7.18"
serde = { version = "1.0", optional = true }
thiserror = "2.0.18"

[dev-dependencies]
criterion = "0.5.1"
serde_json = "1.0"

[[bench]]
name = "parsing"
harness = false

[[bench]]
name = "printing"
harness = false
